name: Continuous Delivery

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Assuming TOKEN is your GitHub token in secrets

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Tag and Release
        id: tag-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Using TOKEN instead of GITHUB_TOKEN
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
