name: Node.js Continuous Deployment

on:
  release:
    types: [published]

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Assuming TOKEN is your GitHub token in secrets

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Deploy to Production
        run: |
          # Replace with your actual deployment commands
          echo "Deploying version ${{ github.event.release.tag_name }} to production..."
          # Example deployment command:
          # ssh user@production-server 'bash -s' < deploy.sh

  rollback:
    runs-on: ubuntu-latest
    needs: []

    if: github.event_name == 'release' && github.event.action == 'deleted'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}

      - name: Rollback to Previous Version
        run: |
          # Replace with your rollback commands
          echo "Rolling back to previous version..."
          # Example rollback command:
          # ssh user@production-server 'bash -s' < rollback.sh

