name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Ensure this version matches your requirements

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Tag and Release on GitHub
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config user.name "mdriyazali"
          git config user.email "mdriyazali254362@gmail.com"
          VERSION=$(node -p "require('./package.json').version")
          git tag -a v${VERSION} -m "Release version ${VERSION}"
          git push origin v${VERSION}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no mdriyaz@23.22.141.26 'cd /home/mdriyaz/sample-node-dev && git pull origin main && npm install && npm run build && pm2 restart app'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
