name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Use the version you want, like '16.x'

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint # Replace with your linting command

      - name: Run tests
        run: npm test # Replace with your testing command

      - name: Build application
        run: npm run build # Replace with your build command

      - name: Tag and Release on GitHub
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # Replace with your GitHub PAT
        run: |
          git config user.name "CI"
          git config user.email "ci@example.com"
          VERSION=$(node -p "require('./package.json').version")
          git tag -a v${VERSION} -m "Release version ${VERSION}"
          git push origin v${VERSION}

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          ssh user@your-server 'cd /path/to/your/app && git pull origin main && npm install && npm run build && pm2 restart app'

