name: Deploy to EC2

on:
  push:
    branches:
      - main  # Adjust to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy application to EC2
        run: |
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} -r ./path/to/your/application mdriyaz@23.22.141.26:/path/on/ec2

      - name: SSH into EC2 and restart application
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} mdriyaz@23.22.141.26 'bash -s' << 'EOF'
            cd /path/on/ec2
            # Commands to stop, update, and restart your application
            pm2 restart your-app-name  # Example for PM2
          EOF
